# Example caller workflow for VS Code Extension CI
# This file shows how to use the reusable VS Code CI workflow
#
# Place this file at: .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main, master]
    paths:
      - '**.ts'
      - '**.json'
      - '.github/workflows/**'
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  vscode-ci:
    uses: jade-codes/syster-pipelines/.github/workflows/vscode-ci.yml@main
    # Optional inputs (shown with defaults):
    # with:
    #   working-directory: '.'
    #   node-version: '20'
