# Example caller workflow for Rust CI
# This file shows how to use the reusable Rust CI workflow
#
# Place this file at: .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust-ci:
    uses: jade-codes/syster-pipelines/.github/workflows/rust-ci.yml@main
    # Optional inputs (shown with defaults):
    # with:
    #   rust-version: 'stable'
    #   working-directory: '.'
