# Example caller workflow for Rust releases
# This file shows how to use the reusable Rust release workflow
#
# Place this file at: .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'  # Pre-releases like v0.1.0-alpha

permissions:
  contents: write

jobs:
  rust-release:
    uses: jade-codes/syster-pipelines/.github/workflows/rust-release.yml@main
    with:
      # For repos with multiple crates, specify publish order:
      crates: 'syster-base,syster-cli,syster-lsp'
      # For single crate repos, omit the crates parameter
      # working-directory: '.'  # Optional: if not in repo root
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

# --- LEGACY TEMPLATE BELOW (for reference only) ---
# The code below is the old template that has been replaced by the reusable workflow above.
# You can delete everything below this line once you've migrated.

# OLD TEMPLATE START

env:
  CARGO_TERM_COLOR: always

jobs:
  # Validate the release before publishing
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Releasing version $VERSION"
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
      
      - name: Package
        run: make package

  # Build release binaries for all platforms
  build:
    name: Build (${{ matrix.target }})
    needs: validate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: syster-linux-x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: syster-linux-x64-musl
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: syster-darwin-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: syster-darwin-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: syster-windows-x64
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install musl tools (Linux musl)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      
      - name: Package
        run: make package TARGET=${{ matrix.target }} ARTIFACT=${{ matrix.artifact }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            ${{ matrix.artifact }}.tar.gz
            ${{ matrix.artifact }}.zip
          if-no-files-found: ignore

  # Publish to crates.io
  publish-crates:
    name: Publish to crates.io
    needs: [validate, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
      
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      
      # Publish in dependency order
      - name: Publish syster-base
        run: cargo publish --package syster-base
        continue-on-error: true  # May already be published
      
      - name: Wait for crates.io to update
        run: sleep 30
      
      - name: Publish syster-cli
        run: cargo publish --package syster-cli
        continue-on-error: true
      
      - name: Wait for crates.io to update
        run: sleep 30
      
      - name: Publish syster-lsp
        run: cargo publish --package syster-lsp
        continue-on-error: true

  # Create GitHub release with binaries
  github-release:
    name: Create GitHub Release
    needs: [validate, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ needs.validate.outputs.version }}
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
          generate_release_notes: true
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
