# Example caller workflow for npm CI
# This file shows how to use the reusable npm CI workflow
#
# Place this file at: .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  npm-ci:
    uses: jade-codes/syster-pipelines/.github/workflows/npm-ci.yml@main
    # Optional inputs (shown with defaults):
    # with:
    #   working-directory: '.'
    #   node-versions: '[18, 20, 22]'
